on:
  pull_request:
    types: [opened, closed]
jobs:
  kang:
    name: Kang
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to post comments
      pull-requests: write

    env:
      TF_ROOT: examples/terraform-project/code
      ZEET_API_KEY: ${{ secrets.ZEET_API_KEY }}
      ZEET_TEAM_ID: 2cb4ab13-c642-4f58-938f-0ca28a6f0189
    steps:
      # Checkout the current PR branch.
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Create Environment
        uses: zeet-co/kang@v0.1
        if: github.event.action == 'opened'
        with:
          args: "start --name=${{ github.head_ref }} --ids=bcf2e9c5-8172-4d7a-95d6-d4fa457b5521,95627c46-1ae9-41d8-bb48-27b89b0ef09d 
            --overrides 'bcf2e9c5-8172-4d7a-95d6-d4fa457b5521:env.NEXT_PUBLIC_PYTHON_API_URL:95627c46-1ae9-41d8-bb48-27b89b0ef09d:deployment.endpoints[0]'
            --overrides 'bcf2e9c5-8172-4d7a-95d6-d4fa457b5521:cpu:1'
            --overrides 'bcf2e9c5-8172-4d7a-95d6-d4fa457b5521:cluster:4461ab27-26bc-4196-aa03-bbf6d4fa9908'
            --overrides 'bcf2e9c5-8172-4d7a-95d6-d4fa457b5521:memory:1G'
            --overrides '95627c46-1ae9-41d8-bb48-27b89b0ef09d:cluster:4461ab27-26bc-4196-aa03-bbf6d4fa9908'"
      - name: Run Destroy Action
        uses: zeet-co/kang@v0.1
        if: github.event.action == 'closed'
        with:
          args: stop --name=${{ github.head_ref }}

      - name: Post Kang comment
        uses: zeet-co/kang@v0.1
        with:
          args: comment --repo=${{ github.repository }} --token=${{ github.token }} --pr=${{ github.event.pull_request.number }} --env-name=${{ github.head_ref }}
